# Generated by Django 5.2 on 2025-05-26 08:15

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=apps.products.models.create_product_random_skull, max_length=20, unique=True),
        ),
    ]
