# Generated by Django 5.2 on 2025-07-03 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productspecification_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='badge',
        ),
    ]
