# Generated by Django 5.2 on 2025-04-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_image_alter_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='Category',
        ),
    ]
