# Generated by Django 5.2 on 2025-04-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productspecification_category'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='badge',
            field=models.ManyToManyField(to='products.badge'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcomparison', to='products.product')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='sessions.session')),
            ],
            options={
                'unique_together': {('session_id', 'product')},
            },
        ),
    ]
