# Generated by Django 5.2 on 2025-06-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productcomparison_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomparison',
            unique_together=set(),
        ),
    ]
