# Generated by Django 5.2 on 2025-06-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcomparison_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomparison',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='productcomparison',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomparison',
            name='session_key',
        ),
    ]
