# Generated by Django 5.2 on 2025-05-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='bade_type',
            field=models.CharField(choices=[('sale', 'SALE'), ('hot', 'HOT'), ('new', 'NEW'), ('best_deal', 'BEST DEAL'), ('sold_out', 'SOLD OUT')], max_length=20),
        ),
    ]
