# Generated by Django 5.2 on 2025-06-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcomparison_added_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductComparison',
        ),
    ]
