# Generated by Django 5.2 on 2025-05-26 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_badge_bade_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product_specification',
        ),
        migrations.AddField(
            model_name='productspecification',
            name='memory',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='size',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productspecification',
            name='storage',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
