# Generated by Django 5.2 on 2025-04-29 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcomparison_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='text',
        ),
    ]
