# Generated by Django 5.2 on 2025-04-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_badge_name_remove_badge_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='show_percentage',
        ),
    ]
