# Generated by Django 5.2 on 2025-05-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productspecification_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_badge', to='products.product'),
        ),
    ]
