# Generated by Django 5.2 on 2025-04-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_badge_show_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product_badge', to='products.product'),
            preserve_default=False,
        ),
    ]
