# Generated by Django 5.2 on 2025-04-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_badge_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='product',
        ),
    ]
