# Generated by Django 5.2 on 2025-04-29 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_badge_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_badge', to='products.product'),
            preserve_default=False,
        ),
    ]
