# Generated by Django 5.2 on 2025-05-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productspecification_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='memory',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='storage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
