# Generated by Django 5.2 on 2025-05-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productspecification_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomparison',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comparison', to='products.product'),
        ),
    ]
