# Generated by Django 5.2 on 2025-05-29 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner'), ('bottom', 'Bottom Banner'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('middle_banner', 'Middle Banner')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(choices=[('best_deal', 'Best Deals'), ('featured_product', 'Featured Products'), ('flash_sale_today', 'FLASH SALE TODAY'), ('best_sellers', 'BEST SELLERS'), ('top_rated', 'TOP RATED'), ('new_arrival', 'NEW ARRIVAL')], max_length=50)),
                ('is_active', models.IntegerField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
