# Generated by Django 5.2 on 2025-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_ad_position_productfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
