# Generated by Django 5.2 on 2025-05-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productfeatures_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product'),
        ),
    ]
