# Generated by Django 5.2 on 2025-05-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_category_alter_productfeatures_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeatures',
            new_name='ProductHighlight',
        ),
    ]
