# Generated by Django 5.2 on 2025-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_productfeatures_producthighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
