# Generated by Django 5.2 on 2025-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner'), ('top-right', 'TOP RIGHT'), ('top-right-two', 'TOP RIGHT TWO'), ('bottom', 'Bottom Banner'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('middle_banner', 'Middle Banner')], max_length=20),
        ),
    ]
