# Generated by Django 5.2 on 2025-06-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_ad_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('top', 'Top Banner'), ('top-right-banner', 'Top Right Banner'), ('top-right-two-banner', 'Top Right Two Banner'), ('bottom', 'Bottom Banner'), ('sidebar', 'Sidebar'), ('popup', 'Popup'), ('middle_banner', 'Middle Banner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
