# Generated by Django 5.2 on 2025-06-02 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_ad_position_alter_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='badge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.badge'),
        ),
    ]
