# Generated by Django 5.2 on 2025-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
