# Generated by Django 5.2 on 2025-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrate',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
