# Generated by Django 5.2 on 2025-06-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_productrate_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrate',
            name='date_rated',
        ),
        migrations.RemoveField(
            model_name='productrate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productrate',
            name='rate_number',
        ),
        migrations.RemoveField(
            model_name='productrate',
            name='rating',
        ),
    ]
