# Generated by Django 5.2 on 2025-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productrating_delete_productrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
