# Generated by Django 5.2 on 2025-06-03 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_productrating_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='highlight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_highlight', to='products.producthighlight'),
        ),
    ]
