# Generated by Django 5.2 on 2025-06-03 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_ad_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlight',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='products.product'),
        ),
    ]
