# Generated by Django 5.2 on 2025-07-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_unique_together'),
        ('products', '0008_alter_topcategory_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.CreateModel(
            name='CartProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('memory', 'size', 'storage')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_product_spec',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cartproductspec'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='specification',
        ),
    ]
