# Generated by Django 5.2 on 2025-07-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartproductspec_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductspec',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_prod_spec', to='cart.cartitem'),
        ),
    ]
