# Generated by Django 5.2 on 2025-07-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(blank=True, null=True)),
                ('size', models.CharField(blank=True, null=True)),
                ('storage', models.CharField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('memory', 'size', 'storage')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_product_spec',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderproductspec'),
            preserve_default=False,
        ),
    ]
