# Generated by Django 5.2 on 2025-05-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('PACKAGING', 'Packaging'), ('ON_THE_ROAD', 'On the Road'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderMessages',
        ),
    ]
