# Generated by Django 5.2 on 2025-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_order_product_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('PACKAGING', 'Packaging'), ('ON_THE_ROAD', 'On the Road'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
