# Generated by Django 5.2 on 2025-07-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='033<function create_random_order_id at 0x0000019167D9ADE0>', max_length=10, unique=True),
        ),
    ]
