# Generated by Django 5.2 on 2025-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_alter_order_user_ordermessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('PACKAGING', 'Packaging'), ('ON_THE_ROAD', 'On the Road'), ('CANCELLED', 'Cancelled'), ('SHIPPED', 'Shipped'), ('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], max_length=20),
        ),
    ]
