# Generated by Django 5.2 on 2025-07-30 18:29

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=apps.orders.models.create_random_order_id, max_length=10, unique=True),
        ),
    ]
