# Generated by Django 5.2 on 2025-08-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uservendor_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='username',
            new_name='other_username',
        ),
    ]
