# Generated by Django 5.2 on 2025-05-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='ban_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_banned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
