# Generated by Django 5.2 on 2025-05-30 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userstatus_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='date_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2025, 5, 30, 23, 13, 44, 719978, tzinfo=datetime.timezone.utc)),
        ),
    ]
