# Generated by Django 5.2 on 2025-09-18 10:48

from django.db import migrations

from django.contrib.auth.hashers import make_password
from dotenv import load_dotenv
import os

load_dotenv()

def create_superuser(apps, scheme_editor):
    User = apps.get_model("accounts", "CustomUser")

    if not User.objects.filter(email=os.getenv('email')):
        User.objects.create_superuser(
            username=os.getenv('username'),
            email=os.getenv('email'),
            password=os.getenv('password'),
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_other_username_additionaluserinfo_related_username_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
