# Generated by Django 5.2 on 2025-05-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userstatus_date_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='date_status',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
