# Generated by Django 5.2 on 2025-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilepicture_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile',
            field=models.ImageField(default='profile/icon-avatar.png', upload_to='profile'),
        ),
    ]
