# Generated by Django 5.2 on 2025-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userstatus_date_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
