# Generated by Django 5.2 on 2025-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profilepicture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
