# Generated by Django 5.2 on 2025-06-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profilepicture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile',
            field=models.ImageField(default='default_profile_pic/icon-avatar.png', upload_to='profile'),
        ),
    ]
