# Generated by Django 5.2 on 2025-06-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profilepicture_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile',
            field=models.ImageField(default='profile/default_profile_pic/icon-avatar.png', upload_to='profile'),
        ),
    ]
