# Generated by Django 5.2 on 2025-07-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_specification'),
        ('products', '0002_alter_productspecification_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'specification')},
        ),
    ]
