# Generated by Django 5.2 on 2025-05-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
