# Generated by Django 5.2 on 2025-06-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session',
            new_name='session_key',
        ),
    ]
