# Generated by Django 5.2 on 2025-05-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_updated_at'),
        ('products', '0017_rename_productfeatures_producthighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_product', to='products.product'),
        ),
    ]
