# Generated by Django 5.2 on 2025-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_session_cart_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistproduct',
            name='session',
        ),
        migrations.AddField(
            model_name='wishlistproduct',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
