# Generated by Django 5.2 on 2025-07-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_unique_together_cartproductspec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_product_spec',
        ),
        migrations.AddField(
            model_name='cartproductspec',
            name='cart_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_prod_spec', to='cart.cartitem'),
            preserve_default=False,
        ),
    ]
