# Generated by Django 5.2 on 2025-06-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_wishlistproduct_session_and_more'),
        ('products', '0008_productcomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_cart', to='products.product'),
        ),
        migrations.AlterField(
            model_name='wishlistproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wish_product', to='products.product'),
        ),
    ]
