# Generated by Django 5.2 on 2025-07-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cartitem_cart_product_spec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductspec',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_prod_spec', to='cart.cartitem'),
        ),
    ]
