# Generated by Django 5.2 on 2025-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostlink',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blogpostlink',
            name='linkedin_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blogpostlink',
            name='pinterest_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blogpostlink',
            name='twitter_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='blogpostlink',
            name='whatsapp_link',
            field=models.URLField(),
        ),
    ]
