# Generated by Django 5.2 on 2025-05-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_blogpostlink_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_comment', to='public.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_images', to='public.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpostlink',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post_links', to='public.blogpost'),
        ),
    ]
