# Generated by Django 5.2 on 2025-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0002_delete_frequentlyaskedquestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active_faq', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OcliconTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='team/%Y/%m/%d/')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=40)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
