# Generated by Django 5.2 on 2025-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_cliconteammember_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='subscribed_at',
        ),
    ]
