# Generated by Django 5.2 on 2025-05-01 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_remove_newslettersubscriber_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
