# Generated by Django 5.2 on 2025-05-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_comments_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='subscribed_at',
        ),
    ]
