# Generated by Django 5.2 on 2025-08-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_additionaluserinfo_other_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='other_username',
            new_name='related_username',
        ),
        migrations.RenameField(
            model_name='additionaluserinfo',
            old_name='email',
            new_name='second_email',
        ),
    ]
