# Generated by Django 5.2 on 2025-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_additionaluserinfo_second_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='second_email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
