# Generated by Django 5.2 on 2026-09-11 20:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_additionaluserinfo_second_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile'),
        ),
    ]
