# Generated by Django 5.2 on 2025-07-29 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderproductspec_orderitem_order_product_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_product_spec',
        ),
        migrations.AddField(
            model_name='orderproductspec',
            name='order_item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_spec', to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
