# Generated by Django 5.2 on 2025-07-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'memory', 'size', 'storage')},
        ),
    ]
