# Generated by Django 5.2 on 2025-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_topcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
