# Generated by Django 5.2 on 2025-07-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_topcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_category', to='products.category'),
        ),
    ]
