# Generated by Django 5.2 on 2026-09-11 20:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ocliconteammembers',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
